Refactor build workflow for stable and dev versions
Refactor build workflow to switch stable and dev build logic, update versioning and notifications accordingly.

diff --git a/.github/workflows/build-on-patch-update.yml b/.github/workflows/build-on-patch-update.yml
--- a/.github/workflows/build-on-patch-update.yml
+++ b/.github/workflows/build-on-patch-update.yml
@@ -281,8 +281,8 @@ jobs:
           NEXT_DEV=""
 
           if [ "$TRIGGER_STABLE" = "1" ] && [ "$TRIGGER_PRERELEASE" = "1" ]; then
-            NEXT_STABLE=$((TAG + 1))
-            NEXT_DEV=$((TAG + 2))
+            NEXT_STABLE=$((TAG + 2))
+            NEXT_DEV=$((TAG + 1))
           elif [ "$TRIGGER_STABLE" = "1" ]; then
             NEXT_STABLE=$((TAG + 1))
           elif [ "$TRIGGER_PRERELEASE" = "1" ]; then
@@ -292,156 +292,9 @@ jobs:
           echo "next_stable_ver=${NEXT_STABLE}" >> "$GITHUB_OUTPUT"
           echo "next_dev_ver=${NEXT_DEV}" >> "$GITHUB_OUTPUT"
 
-  build-stable:
-    needs: check-patch
-    if: needs.check-patch.outputs.trigger_stable == '1'
-    permissions: write-all
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout (Main)
-        uses: actions/checkout@v6
-        with:
-          ref: main
-          fetch-depth: 0
-          submodules: true
-
-      - name: Setup Java (Zulu 17)
-        uses: actions/setup-java@v5
-        with:
-          distribution: "zulu"
-          java-version: "17"
-
-      - name: Notify Telegram (New Stable Patch)
-        env:
-          TG_TOKEN: ${{ secrets.TG_TOKEN }}
-          TG_CHAT: "@revanced_builder"
-          TG_THREAD_ID: "345"
-        run: |
-          NL=$'\n'
-          MSG="*New Patch Detected!*${NL}"
-          if [ "${{ needs.check-patch.outputs.sa_new }}" != "${{ needs.check-patch.outputs.sa_old }}" ]; then
-            MSG+="${NL}• [Advanced](https://github.com/anddea/revanced-patches/releases/tag/${{ needs.check-patch.outputs.sa_new }}):${NL}Old: \`${{ needs.check-patch.outputs.sa_old }}\` → New: \`${{ needs.check-patch.outputs.sa_new }}\`${NL}"
-          fi
-          if [ "${{ needs.check-patch.outputs.so_new }}" != "${{ needs.check-patch.outputs.so_old }}" ]; then
-            MSG+="${NL}• [Official](https://github.com/ReVanced/revanced-patches/releases/tag/${{ needs.check-patch.outputs.so_new }}):${NL}Old: \`${{ needs.check-patch.outputs.so_old }}\` → New: \`${{ needs.check-patch.outputs.so_new }}\`${NL}"
-          fi
-          if [ "${{ needs.check-patch.outputs.se_new }}" != "${{ needs.check-patch.outputs.se_old }}" ]; then
-            MSG+="${NL}• [Extended](https://github.com/inotia00/revanced-patches/releases/tag/${{ needs.check-patch.outputs.se_new }}):${NL}Old: \`${{ needs.check-patch.outputs.se_old }}\` → New: \`${{ needs.check-patch.outputs.se_new }}\`${NL}"
-          fi
-          MSG+="${NL}[Triggering new build...](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)${NL}${NL}@revanced\\_builder"
-          MSG=${MSG:0:9450}
-          curl -X POST \
-            --data-urlencode "parse_mode=Markdown" \
-            --data-urlencode "disable_web_page_preview=true" \
-            --data-urlencode "text=${MSG}" \
-            --data-urlencode "chat_id=${TG_CHAT}" \
-            --data-urlencode "message_thread_id=${TG_THREAD_ID}" \
-            "https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
-
-      - name: Build Modules and APKs (Stable)
-        run: |
-          rm -rf build
-          mkdir -p build
-          ./build.sh .github/misc/config.stable.updated.toml
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
-          NEXT_VER_CODE: ${{ needs.check-patch.outputs.next_stable_ver }}
-
-      - name: Get Output (Stable)
-        id: get_output_stable
-        run: |
-          DELIM="$(openssl rand -hex 8)"
-          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
-          cat build.md >> "$GITHUB_OUTPUT"
-          echo "${DELIM}" >> "$GITHUB_OUTPUT"
-          cp -f build.md build.tmp
-
-      - name: Upload to Release (Stable)
-        uses: svenstaro/upload-release-action@v2
-        with:
-          body: ${{ steps.get_output_stable.outputs.BUILD_LOG }}
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: ./build/*
-          file_glob: true
-          release_name: Build No. ${{ needs.check-patch.outputs.next_stable_ver }}
-          tag: ${{ needs.check-patch.outputs.next_stable_ver }}
-          overwrite: true
-
-      - name: Update Changelog and Magisk Update JSON (Stable)
-        run: |
-          git checkout -f update || git switch --discard-changes --orphan update
-          cp -f build.tmp build.md
-          get_update_json() {
-            echo "{
-            \"version\": \"$1\",
-            \"versionCode\": ${{ needs.check-patch.outputs.next_stable_ver }},
-            \"zipUrl\": \"$2\",
-            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
-          }"
-          }
-          cd build || { echo "build folder not found"; exit 1; }
-          for OUTPUT in *magisk*.zip; do
-            [ "$OUTPUT" = "*magisk*.zip" ] && continue
-            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
-            if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
-            UPDATE_JSON="${UPDATE_JSON##*/}"
-            VER=$(echo "$ZIP_S" | grep version=)
-            VER="${VER##*=}"
-            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ needs.check-patch.outputs.next_stable_ver }}/${OUTPUT}"
-            get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
-          done
-          cd ..
-          find . -name "*-update.json" | grep . || : >dummy-update.json
-
-      - name: Commit Updated Build MD and Update JSON Files (Stable)
-        uses: stefanzweifel/git-auto-commit-action@v7
-        with:
-          branch: update
-          skip_checkout: true
-          file_pattern: build.md *-update.json
-          commit_message: Bump version ${{ needs.check-patch.outputs.next_stable_ver }}
-
-      - name: Notify Telegram (Stable Build Complete)
-        env:
-          TG_TOKEN: ${{ secrets.TG_TOKEN }}
-          TG_CHAT: "@revanced_builder"
-          TG_THREAD_ID: "262"
-        run: |
-          cd build || exit 1
-          NL=$'\n'
-          APKS=""
-          MODULES=""
-          HAS_MODULES=false
-          for OUTPUT in *; do
-            DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ needs.check-patch.outputs.next_stable_ver }}/${OUTPUT}"
-            if [[ $OUTPUT = *.apk ]]; then
-              APKS+="${NL}${NL}[${OUTPUT}](${DL_URL})"
-            elif [[ $OUTPUT = *.zip ]]; then
-              MODULES+="${NL}${NL}[${OUTPUT}](${DL_URL})"
-              HAS_MODULES=true
-            fi
-          done
-          MODULES=${MODULES#"$NL"}
-          APKS=${APKS#"$NL"}
-          BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g; s/^- /↪ /g; /^==/d;' ../build.md)"
-          MSG="*Build No. ${{ needs.check-patch.outputs.next_stable_ver }}*${NL}${NL}${BODY}${NL}${NL}"
-          if [ "$HAS_MODULES" = true ]; then
-            MSG+="*Modules:*${MODULES}${NL}${NL}"
-          fi
-          MSG+="*APKs:*${APKS}"
-          MSG=${MSG:0:9450}
-          curl -X POST \
-            --data-urlencode "parse_mode=Markdown" \
-            --data-urlencode "disable_web_page_preview=true" \
-            --data-urlencode "text=${MSG}" \
-            --data-urlencode "chat_id=${TG_CHAT}" \
-            --data-urlencode "message_thread_id=${TG_THREAD_ID}" \
-            "https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
-
   build-dev:
-    needs: [check-patch, build-stable]
-    if: always() && needs.check-patch.outputs.trigger_prerelease == '1'
+    needs: check-patch
+    if: needs.check-patch.outputs.trigger_prerelease == '1'
     permissions: write-all
     runs-on: ubuntu-latest
     steps:
@@ -587,8 +440,155 @@ jobs:
             --data-urlencode "message_thread_id=${TG_THREAD_ID}" \
             "https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
 
+  build-stable:
+    needs: [check-patch, build-dev]
+    if: always() && needs.check-patch.outputs.trigger_stable == '1'
+    permissions: write-all
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout (Main)
+        uses: actions/checkout@v6
+        with:
+          ref: main
+          fetch-depth: 0
+          submodules: true
+
+      - name: Setup Java (Zulu 17)
+        uses: actions/setup-java@v5
+        with:
+          distribution: "zulu"
+          java-version: "17"
+
+      - name: Notify Telegram (New Stable Patch)
+        env:
+          TG_TOKEN: ${{ secrets.TG_TOKEN }}
+          TG_CHAT: "@revanced_builder"
+          TG_THREAD_ID: "345"
+        run: |
+          NL=$'\n'
+          MSG="*New Patch Detected!*${NL}"
+          if [ "${{ needs.check-patch.outputs.sa_new }}" != "${{ needs.check-patch.outputs.sa_old }}" ]; then
+            MSG+="${NL}• [Advanced](https://github.com/anddea/revanced-patches/releases/tag/${{ needs.check-patch.outputs.sa_new }}):${NL}Old: \`${{ needs.check-patch.outputs.sa_old }}\` → New: \`${{ needs.check-patch.outputs.sa_new }}\`${NL}"
+          fi
+          if [ "${{ needs.check-patch.outputs.so_new }}" != "${{ needs.check-patch.outputs.so_old }}" ]; then
+            MSG+="${NL}• [Official](https://github.com/ReVanced/revanced-patches/releases/tag/${{ needs.check-patch.outputs.so_new }}):${NL}Old: \`${{ needs.check-patch.outputs.so_old }}\` → New: \`${{ needs.check-patch.outputs.so_new }}\`${NL}"
+          fi
+          if [ "${{ needs.check-patch.outputs.se_new }}" != "${{ needs.check-patch.outputs.se_old }}" ]; then
+            MSG+="${NL}• [Extended](https://github.com/inotia00/revanced-patches/releases/tag/${{ needs.check-patch.outputs.se_new }}):${NL}Old: \`${{ needs.check-patch.outputs.se_old }}\` → New: \`${{ needs.check-patch.outputs.se_new }}\`${NL}"
+          fi
+          MSG+="${NL}[Triggering new build...](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)${NL}${NL}@revanced\\_builder"
+          MSG=${MSG:0:9450}
+          curl -X POST \
+            --data-urlencode "parse_mode=Markdown" \
+            --data-urlencode "disable_web_page_preview=true" \
+            --data-urlencode "text=${MSG}" \
+            --data-urlencode "chat_id=${TG_CHAT}" \
+            --data-urlencode "message_thread_id=${TG_THREAD_ID}" \
+            "https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
+
+      - name: Build Modules and APKs (Stable)
+        run: |
+          rm -rf build
+          mkdir -p build
+          ./build.sh .github/misc/config.stable.updated.toml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
+          NEXT_VER_CODE: ${{ needs.check-patch.outputs.next_stable_ver }}
+
+      - name: Get Output (Stable)
+        id: get_output_stable
+        run: |
+          DELIM="$(openssl rand -hex 8)"
+          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+          cat build.md >> "$GITHUB_OUTPUT"
+          echo "${DELIM}" >> "$GITHUB_OUTPUT"
+          cp -f build.md build.tmp
+
+      - name: Upload to Release (Stable)
+        uses: svenstaro/upload-release-action@v2
+        with:
+          body: ${{ steps.get_output_stable.outputs.BUILD_LOG }}
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: ./build/*
+          file_glob: true
+          release_name: Build No. ${{ needs.check-patch.outputs.next_stable_ver }}
+          tag: ${{ needs.check-patch.outputs.next_stable_ver }}
+          overwrite: true
+
+      - name: Update Changelog and Magisk Update JSON (Stable)
+        run: |
+          git checkout -f update || git switch --discard-changes --orphan update
+          cp -f build.tmp build.md
+          get_update_json() {
+            echo "{
+            \"version\": \"$1\",
+            \"versionCode\": ${{ needs.check-patch.outputs.next_stable_ver }},
+            \"zipUrl\": \"$2\",
+            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
+          }"
+          }
+          cd build || { echo "build folder not found"; exit 1; }
+          for OUTPUT in *magisk*.zip; do
+            [ "$OUTPUT" = "*magisk*.zip" ] && continue
+            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+            if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+            UPDATE_JSON="${UPDATE_JSON##*/}"
+            VER=$(echo "$ZIP_S" | grep version=)
+            VER="${VER##*=}"
+            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ needs.check-patch.outputs.next_stable_ver }}/${OUTPUT}"
+            get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+          done
+          cd ..
+          find . -name "*-update.json" | grep . || : >dummy-update.json
+
+      - name: Commit Updated Build MD and Update JSON Files (Stable)
+        uses: stefanzweifel/git-auto-commit-action@v7
+        with:
+          branch: update
+          skip_checkout: true
+          file_pattern: build.md *-update.json
+          commit_message: Bump version ${{ needs.check-patch.outputs.next_stable_ver }}
+
+      - name: Notify Telegram (Stable Build Complete)
+        env:
+          TG_TOKEN: ${{ secrets.TG_TOKEN }}
+          TG_CHAT: "@revanced_builder"
+          TG_THREAD_ID: "262"
+        run: |
+          cd build || exit 1
+          NL=$'\n'
+          APKS=""
+          MODULES=""
+          HAS_MODULES=false
+          for OUTPUT in *; do
+            DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ needs.check-patch.outputs.next_stable_ver }}/${OUTPUT}"
+            if [[ $OUTPUT = *.apk ]]; then
+              APKS+="${NL}${NL}[${OUTPUT}](${DL_URL})"
+            elif [[ $OUTPUT = *.zip ]]; then
+              MODULES+="${NL}${NL}[${OUTPUT}](${DL_URL})"
+              HAS_MODULES=true
+            fi
+          done
+          MODULES=${MODULES#"$NL"}
+          APKS=${APKS#"$NL"}
+          BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g; s/^- /↪ /g; /^==/d;' ../build.md)"
+          MSG="*Build No. ${{ needs.check-patch.outputs.next_stable_ver }}*${NL}${NL}${BODY}${NL}${NL}"
+          if [ "$HAS_MODULES" = true ]; then
+            MSG+="*Modules:*${MODULES}${NL}${NL}"
+          fi
+          MSG+="*APKs:*${APKS}"
+          MSG=${MSG:0:9450}
+          curl -X POST \
+            --data-urlencode "parse_mode=Markdown" \
+            --data-urlencode "disable_web_page_preview=true" \
+            --data-urlencode "text=${MSG}" \
+            --data-urlencode "chat_id=${TG_CHAT}" \
+            --data-urlencode "message_thread_id=${TG_THREAD_ID}" \
+            "https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
+
   cleanup:
-    needs: [check-patch, build-stable, build-dev]
+    needs: [check-patch, build-dev, build-stable]
     if: always() && (needs.check-patch.outputs.trigger_prerelease == '1' || needs.check-patch.outputs.trigger_stable == '1')
     runs-on: ubuntu-latest
     permissions:
